import { useState } from "react";

export default function CarbonMarketGuide() {
  const [openSection, setOpenSection] = useState(null);

  const sections = [
    {
      title: "What Is a Carbon Credit?",
      content: (
        <>
          <p>
          A carbon credit is a tradable certificate that represents the reduction, avoidance, 
          or removal of one metric tonne of carbon dioxide (CO2) or its equivalent greenhouse gas.
          </p>

          <p className="mt-4">
          Companies that reduce or avoid emissions earn credits. 
          Companies that are unable to reduce fast enough buy those credits to offset their remaining emissions.
          This system turns climate action into a financial incentive.
          </p>

          <p className="mt-4">
          The logic is simple: if you pollute less than your limit, you earn credits you can sell. 
          If you pollute more, you must buy credits from someone who polluted less.
          One credit equals one tonne of CO2 reduced or removed. That is the universal unit across all carbon markets globally.
          </p>
        </>
      ),
    },

    {
      title: "Why India? Understanding the Opportunity",
      content: (
        <>
          <p>
          India is the world’s third-largest emitter of greenhouse gases. 
          That sounds like a problem, but in the carbon market world, it is also an opportunity.
          Because India has so many industries still transitioning to cleaner technologies, 
          there is an enormous pipeline of projects that can generate carbon credits.
          </p>

          <p className="mt-4">
          Solar farms, wind energy plants, clean cookstoves, biogas systems, afforestation projects, agricultural reforms, 
          waste management sites, and more can all produce verified credits.
          India has been one of the largest suppliers of carbon credits to the global voluntary market for over a decade.
          As of early 2026, the country is now formalizing a domestic compliance market through the Carbon Credit Trading Scheme (CCTS), 
          which adds an entirely new demand layer on top of the existing voluntary market.
          </p>

          <p className="mt-4">
          The Indian carbon credit market is estimated to be worth over $1 billion today, with projections pointing significantly higher as CCTS compliance trading begins.
          This creates real business for carbon credit companies in India, ranging from large listed firms to niche climate tech startups.
          </p>
        </>
      ),
    },

    {
      title: "Two Types of Carbon Markets in India",
      content: (
        <>
          <h4 className="text-lg font-semibold text-slate-900">
            1. Compliance Carbon Market
          </h4>

          <p className="mt-2">
            A compliance market is a government-regulated system where
            organizations in specific sectors must meet established emissions
            targets.
          </p>

          <h4 className="mt-6 text-lg font-semibold text-slate-900">
            2. Voluntary Carbon Market
          </h4>

          <p className="mt-2">
            The voluntary carbon market allows companies and organizations to
            purchase carbon credits voluntarily to support climate commitments,
            offset emissions, and work toward sustainability goals.
          </p>
        </>
      ),
    },

    {
      title: "What Projects Generate Carbon Credits?",
      content: (
        <>
          <p>
            Carbon credits can be generated by many different types of climate
            and environmental projects.
          </p>

          <div className="mt-5 grid gap-3 sm:grid-cols-2">
            {[
              "Renewable Energy",
              "Energy Efficiency",
              "Clean Cooking Solutions",
              "Waste Management",
              "Agriculture & Soil Carbon",
              "Afforestation & Reforestation",
              "Electric Mobility",
              "Biochar & Agricultural Waste",
            ].map((project) => (
              <div
                key={project}
                className="rounded-xl bg-slate-100 px-4 py-3 text-sm font-medium text-slate-700"
              >
                {project}
              </div>
            ))}
          </div>
        </>
      ),
    },

    {
      title: "Challenges Facing Carbon Markets in India",
      content: (
        <>
          <div className="space-y-5">
            <div>
              <h4 className="font-semibold text-slate-900">
                Credit Quality & Greenwashing
              </h4>

              <p className="mt-1">
                Ensuring that carbon credits represent genuine, measurable, and
                additional emission reductions remains one of the industry's
                biggest challenges.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-slate-900">
                Market Price Volatility
              </h4>

              <p className="mt-1">
                Carbon credit prices can fluctuate based on demand, regulation,
                market confidence, and the quality of individual projects.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-slate-900">
                Verification Complexity
              </h4>

              <p className="mt-1">
                Measuring, verifying, and registering emission reductions can
                be expensive and time-consuming, especially for smaller
                projects.
              </p>
            </div>

            <div>
              <h4 className="font-semibold text-slate-900">
                Implementation Challenges
              </h4>

              <p className="mt-1">
                Developing new carbon market infrastructure requires clear
                regulations, trusted verification systems, and efficient market
                mechanisms.
              </p>
            </div>
          </div>
        </>
      ),
    },

    {
      title: "European vs Indian Carbon Market Prices",
      content: (
        <>
          <p>
            Carbon credit prices vary significantly depending on the market,
            project type, and quality of the emission reduction.
          </p>

          <div className="mt-6 grid gap-5 md:grid-cols-2">

            <div className="rounded-2xl border border-green-100 bg-green-50 p-5">
              <h4 className="text-lg font-bold text-slate-800">
                European Market
              </h4>

              <ul className="mt-4 space-y-3 text-sm text-slate-600">
                <li>Compliance Market (EU ETS): Official EU allowances trade around €82.67 to €84.00 per ton.</li>
                <li>Voluntary Nature-Based Credits: Lower-cost offsets in Europe range from €7 to €24 per ton depending on the specific project integrity.</li>
                <li>Cutting-Edge Tech Removals: Advanced technological carbon removal credits cost between €150 and €500 per ton</li>
              </ul>
            </div>

            <div className="rounded-2xl border border-green-100 bg-green-50 p-5">
              <h4 className="text-lg font-bold text-slate-800">
                Indian Market
              </h4>

              <ul className="mt-4 space-y-3 text-sm text-slate-600">
                <li>Compliance Market (CCTS)₹830 to ₹1,000 (~$10 to $12 USD)Newly launched national system governing heavy industries (cement, aluminium, etc.).</li>
                <li>Voluntary Offsets₹200 to ₹500 (~$2.50 to $6 USD)Basic renewable energy or efficiency credits driven by self-regulated ESG goals.</li>
                <li>Premium / High-Integrity₹1,200 to ₹2,500 (~$15 to $30 USD)Nature-based projects, agroforestry, and blue carbon (mangroves) with high social co-benefits.</li>
                <li>Technological Removals₹8,800 to ₹12,500 (~€105 to €150 / $120+ USD)Artisanal and industrial-scale biochar projects, which represent India's lowest-cost permanent removal asset.</li>
              </ul>
            </div>

          </div>
        </>
      ),
    },
  ];

  const toggleSection = (index) => {
    setOpenSection(openSection === index ? null : index);
  };

  return (
    <section
      id="carbon-guide"
      className="bg-gradient-to-b from-slate-50 via-white to-slate-50 py-24"
    >
      <div className="mx-auto max-w-5xl px-6">

        {/* SECTION HEADER */}

        <div className="mx-auto max-w-3xl text-center">

          <p className="text-sm font-bold uppercase tracking-[0.3em] text-green-700">
            Carbon Market Knowledge
          </p>

          <h2 className="mt-4 text-4xl font-bold tracking-tight text-slate-900 md:text-5xl">
            Understanding the World of Carbon Credits
          </h2>

          <p className="mt-5 text-lg leading-8 text-slate-600">
            Explore the fundamentals of carbon markets, understand how carbon
            credits work, and discover the opportunities shaping India's
            growing climate economy.
          </p>

        </div>


        {/* EXPANDABLE SECTIONS */}

        <div className="mt-14 space-y-4">

          {sections.map((section, index) => {

            const isOpen = openSection === index;

            return (
              <div
                key={section.title}
                className={`overflow-hidden rounded-2xl border transition-all duration-300 ${
                  isOpen
                    ? "border-green-200 bg-white shadow-lg shadow-green-100/40"
                    : "border-slate-200 bg-white"
                }`}
              >

                {/* HEADER BUTTON */}

                <button
                  onClick={() => toggleSection(index)}
                  className="flex w-full items-center justify-between gap-6 px-6 py-6 text-left md:px-8"
                >

                  <span className="text-lg font-semibold text-slate-900 md:text-xl">
                    {section.title}
                  </span>


                  {/* PLUS / MINUS */}

                  <span
                    className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-full border text-xl transition ${
                      isOpen
                        ? "border-green-700 bg-green-700 text-white"
                        : "border-slate-300 text-slate-600"
                    }`}
                  >
                    {isOpen ? "−" : "+"}
                  </span>

                </button>


                {/* EXPANDED CONTENT */}

                {isOpen && (
                  <div className="border-t border-slate-100 px-6 pb-7 pt-6 text-base leading-7 text-slate-600 md:px-8">

                    {section.content}

                  </div>
                )}

              </div>
            );
          })}

        </div>

      </div>
    </section>
  );
}